### ISSUE TITLE
Python Version under 3.10

### ISSUE THREAD

**Issue by ELFALLAH02** [imdreamer2018/streamlit-date-picker#1]
I currently use Python 3.8, but this package only works on Python 3.10. Unfortunately, upgrading to Python 3.10 is not an option as it is a large project.

**Comment by imdreamer2018** [comment]
I will downgrade to python3.8 in next version.

**Comment by imdreamer2018** [comment]
Hi @ELFALLAH02 
downgrade python Issue has bean fixed in new version,
pip install streamlit-date-picker==0.0.3

If you has any question, you can reply in this issue, TKS~

**Comment by ELFALLAH02** [comment]
thank you so much
