### ISSUE TITLE
Flickering Issue

### ISSUE THREAD

**Issue by PFacheris** [imdreamer2018/streamlit-date-picker#4]
When constructing the selector using
```
date_range = date_range_picker(
    picker_type=PickerType.month.string_value,
    start=-3, end=0, unit=Unit.months.string_value,
    key='range_picker',
    refresh_button={
        'is_show': True, 'button_name': 'Refresh last 30min',
        'refresh_date': -30,
        'unit': Unit.minutes.string_value
    }
)
```

On an otherwise empty page in a multi-page app I get the following flickering issue when attempting to interact with the component:
https://github.com/imdreamer2018/streamlit-date-picker/assets/1783057/869119b7-2115-4f61-8d11-3db468ee64da

It makes it nearly impossible to interact/use this component as a result. This seems to have been resolved by downgrading to streamlit==1.31 so this may be a duplicate of #3.

**Comment by imdreamer2018** [comment]
Hi, @PFacheris 
Flickering Issue has bean fixed in new version,
`pip install streamlit-date-picker==0.0.3`

If you has any question, you can reply in this issue, TKS~
