### ISSUE TITLE
MarshallComponentException: ('Could not convert component args to JSON', TypeError('Object of type PickerType is not JSON serializable'))

### ISSUE THREAD

**Issue by bo-wu** [imdreamer2018/streamlit-date-picker#5]
Hi, 
   Thanks for this widget, I would like to try it. However,  paste the time range picker example and run it, will give error like the title.
`
MarshallComponentException: ('Could not convert component args to JSON', TypeError('Object of type PickerType is not JSON serializable'))
`
If change `picker_type=PickerType.time.string_value` and without other parameters , the widget can show up.  but it shows the invalid date time.   Both `start=default_start`  and `start=str(default_start)` or `start=default_start.strftime("%Y-%m-%d %H:%M:%S")` not work. BTW, python version is 3.10.12

What is the problem?

**Comment by imdreamer2018** [comment]
picker_type=PickerType.time.string_value has deprecated, please refer to latest usage from README

**Comment by bo-wu** [comment]
> picker_type=PickerType.time.string_value has deprecated, please refer to latest usage from README

Sure. The problem is that using  `picker_type=PickerType.time` will report error as the title @imdreamer2018

**Comment by bo-wu** [comment]
I tried streamlit 1.32 again( stop app, install and run again), the widget works well. It seems not work with streamlit 1.34

**Comment by bo-wu** [comment]
It is wired, I shutdown the streamlit run command and rerun again, everything works fine.  Thanks a lot
