### ISSUE TITLE
Support pick date and time in picker

### ISSUE THREAD

**Issue by cool9203** [imdreamer2018/streamlit-date-picker#8]
Now `Time Picker` just can pick time or date.
Not support pick date and time at same time.

Like `Time Ranger Picker` can pick date and time.

Thanks

Example:

![image](https://github.com/imdreamer2018/streamlit-date-picker/assets/29609607/c2d4506b-5a34-4ab4-87f4-15a2a7350538)

**Comment by imdreamer2018** [comment]
Hi @cool9203 
You can temporarily enter the time in the Time Picker input box，Like this
![image](https://github.com/imdreamer2018/streamlit-date-picker/assets/35443799/803eba47-d410-4dc1-ac8c-b243737b0d5f)

Time Time Picker can pick date and time will be implemented in next version.  TKS~

**Comment by imdreamer2018** [comment]
@cool9203 Hi install the lastest version
`pip install streamlit-date-picker`

![image](https://github.com/user-attachments/assets/2f7a6990-1562-4235-8744-9a48157ac02c)
