### ISSUE TITLE
Can you add component titles and component size functions

### ISSUE THREAD

**Issue by SZeCloud** [imdreamer2018/streamlit-date-picker#9]
There is a significant difference in the style of components compared to streamlit's native components, and if they are laid out on the same line, it may appear uncoordinated

**Comment by imdreamer2018** [comment]
sorry, streamlit-date-picker implement by [antd component](https://ant-design.antgroup.com/components/date-picker-cn), there is no way to avoid differences with streamlit's native components in temporary.
